apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-tumor-segmentation
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: brain-tumor-segmentation
  template:
    metadata:
      labels:
        app: brain-tumor-segmentation
    spec:
      containers:
      - name: trainer
        image: moe-inference:latest
        env:
          - name: WANDB_API_KEY
            value: "d179d52a12c57e77a7406596c409e3dfbda8de19" 
          - name: MASTER_ADDR
            value: "localhost" 
          - name: MASTER_PORT
            value: "12355" 
          - name: RANK
            valueFrom:
              fieldRef:
                fieldPath: metadata.name 
          - name: WORLD_SIZE
            value: "4"
        imagePullPolicy: Never 
        command: ["streamlit"]
        args: ["run", "app.py"]
        resources:
          requests:
            cpu: "1000m" 
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        ports:
          - containerPort: 8501
        volumeMounts:
        - mountPath: /app/output
          name: output-vol
      volumes:
      - name: output-vol
        emptyDir: {} 

---
apiVersion: v1
kind: Service
metadata:
  name: brain-tumor-segmentation-service
spec:
  type: NodePort
  selector:
    app: brain-tumor-segmentation
  ports:
    - port: 80           # Exposed externally
      targetPort: 8501   # Container port Streamlit listens to
      nodePort: 30001 
